apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  type: LoadBalancer
  selector:
    app: blog
  ports:
    - protocol: TCP
      port: 80         # Exposes the service on port 80
      targetPort: 80   # Forwards to containerPort 80 in the pod
      name: http