apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: github-actions-token
  namespace: webapps # Namespace where the service account is created
  annotations:
    kubernetes.io/service-account.name: git-actions-svc # Name of the service account.